### PR TITLE
Remove --nodiscover from non bootnodes

### PR DESCRIPTION
**Pull request by rodion-lim-partior**
Currently when starting multiple members Quorum network, there is an error being thrown when trying to register organization and nodes for members whom are not part of the bootnode (i.e. bootnodes are used for auto discovery of peers).

Removing --nodiscover flag from all members prevent nodes from being discovered by the bootnode. This PR is raised to retain the --nodiscover flag on the bootnode itself, while removing the flag on the remaining nodes so that they can be connected in the same network.

### CODE REVIEW

**Review by jimthematrix — CHANGES_REQUESTED** [review]
@rodion-lim-partior thanks for proposing the PR. please check the suggested changes I made below. after that it should work as expected.

note that with this setup, such that the bootnode (the node at index 0) has discovery turn on whereas the rest of the nodes have discovery turned off, only the bootnode is connected to the other nodes, while any other nodes are only connected to the bootnode, but not to each other. while this is not ideal, it serves the purpose because the only block signer in the network is the node at index 0. This means the network will function properly, as long as no other nodes are voted in as additional block signers.

Getting all nodes to be connected with each other will take more work. If that's desirable or becomes mandatory in the future, we can work on adding that.

**Comment by EnriqueL8** [comment]
Will merge these changes, and @jimthematrix will include his proposed changes in a new PR. I believe getting this working for v1.3.1 is critical so going ahead and merging

**Review by EnriqueL8 — APPROVED** [review]
As explained above, merging and Jim will raise a PR with proposed fixes! Thanks for the contribution @rodion-lim-partior 😃

**Comment by rodion-lim-partior** [comment]
@jimthematrix, apologies for the late reply, the original PR that I raised for adding Quorum/Tessera support is in line with your suggested changes. I kept --no-discover due to this commit that was added by Peter https://github.com/hyperledger/firefly-cli/commit/e1707eaabff8190afe5abdd959993301795c085a, I wasn't sure if no-discover was added due to unwanted connections from people outside the network. I tested your changes, it worked fine on our environments.

**Pull request merged**
