### PR TITLE
Firefly besu clique

### PR DESCRIPTION
**Pull request by sukrut29**
"Signed-off-by: sukrut29 <sukrut.sathaye@sttech.de>"

### CODE REVIEW

**Comment by nguyer** [comment]
Sukrut and I chatted directly about this, but it looks like tokens functionality is not working correctly with this configuration. When I run the E2E tests against this stack, I see ethconnect not getting events from the blockchain for transactions submitted by the token connector, which is causing tests to fail right now. Some more investigation will be needed into why this is happening, but unfortunately I do not have the cycles at the moment to look into it.

**Comment by sukrut29** [comment]
> Sukrut and I chatted directly about this, but it looks like tokens functionality is not working correctly with this configuration. When I run the E2E tests against this stack, I see ethconnect not getting events from the blockchain for transactions submitted by the token connector, which is causing tests to fail right now. Some more investigation will be needed into why this is happening, but unfortunately I do not have the cycles at the moment to look into it.

Your reply is much appreciated. :)
Thank you for taking out the time to review and test. Whenever you have time, we can look into it next and get it sorted.

**Review by nguyer — APPROVED** [review]
This is really great! Thank you @sukrut29 for contributing this!

There may be some room for additional simplification of the Besu config directory, but I think we should merge this, and perhaps we can continue to refine it later.

Thanks again!

**Comment by sukrut29** [comment]
Thanks a lot for your support @nguyer  and constant availability for communications :)
It was a pleasure to collaborate with you and contribute!

**Pull request merged**
