### PR TITLE
Firefly on besu ibft2

### PR DESCRIPTION
**Pull request by sukrut29**
Signed-off-by: sukrut29 <sukrut.sathaye@sttech.de>

### CODE REVIEW

**Comment by nguyer** [comment]
@sukrut29 Thank you for contributing this! I will start reviewing it. In the meantime, it looks like the DCO bot has flagged that some or all commits do not have proper sign-off. Could you please check here for details: https://github.com/hyperledger/firefly-cli/pull/117/checks?check_run_id=4082447375

Thanks!

**Comment by nguyer** [comment]
I build this branch locally and tried to create a new besu stack with `ff init besu 2 -b besu` and got the following:

```
➜  ~ ./ff start besu -v --no-rollback
reading stack config... done
this will take a few seconds longer since this is the first time you're running this stack...
starting FireFly stack 'besu'... initializing blockchain node
writing data exchange certs
/usr/local/bin/docker run --rm -v besu_dataexchange_0:/dest alpine mkdir -p /dest/peer-certs
/usr/local/bin/docker run --rm -v /Users/nguyer/.firefly/stacks/besu/data/dataexchange_0/config.json:/source/config.json -v besu_dataexchange_0:/dest alpine cp /source/config.json /dest/config.json
/usr/local/bin/docker run --rm -v /Users/nguyer/.firefly/stacks/besu/data/dataexchange_0/cert.pem:/source/cert.pem -v besu_dataexchange_0:/dest alpine cp /source/cert.pem /dest/cert.pem
/usr/local/bin/docker run --rm -v /Users/nguyer/.firefly/stacks/besu/data/dataexchange_0/key.pem:/source/key.pem -v besu_dataexchange_0:/dest alpine cp /source/key.pem /dest/key.pem
/usr/local/bin/docker run --rm -v besu_dataexchange_1:/dest alpine mkdir -p /dest/peer-certs
/usr/local/bin/docker run --rm -v /Users/nguyer/.firefly/stacks/besu/data/dataexchange_1/config.json:/source/config.json -v besu_dataexchange_1:/dest alpine cp /source/config.json /dest/config.json
/usr/local/bin/docker run --rm -v /Users/nguyer/.firefly/stacks/besu/data/dataexchange_1/cert.pem:/source/cert.pem -v besu_dataexchange_1:/dest alpine cp /source/cert.pem /dest/cert.pem
/usr/local/bin/docker run --rm -v /Users/nguyer/.firefly/stacks/besu/data/dataexchange_1/key.pem:/source/key.pem -v besu_dataexchange_1:/dest alpine cp /source/key.pem /dest/key.pem
copying firefly.core to firefly_core_0
/usr/local/bin/docker run --rm -v /Users/nguyer/.firefly/stacks/besu/configs/firefly_core_0.yml:/source/firefly_core_0.yml -v besu_firefly_core_0:/dest alpine cp /source/firefly_core_0.yml /dest/firefly.core
copying firefly.core to firefly_core_1
/usr/local/bin/docker run --rm -v /Users/nguyer/.firefly/stacks/besu/configs/firefly_core_1.yml:/source/firefly_core_1.yml -v besu_firefly_core_1:/dest alpine cp /source/firefly_core_1.yml /dest/firefly.core
starting FireFly dependencies
/usr/local/bin/docker-compose up -d
service "besu" has neither an image nor a build context specified: invalid compose project
Error: docker-compose up -d
Failed [15]
Usage:
  ff start <stack_name> [flags]

Flags:
  -h, --help          help for start
  -b, --no-rollback   Do not automatically rollback changes if first time setup fails

Global Flags:
      --ansi string   control when to print ANSI control characters ("never"|"always"|"auto") (default "auto") (default "auto")
  -v, --verbose       verbose log output

Error: docker-compose up -d
Failed [15]
```

**Comment by sukrut29** [comment]
I always initialized and started the stacks with --blockchain-provider=besu flag

**Comment by sukrut29** [comment]
Can you share the docker-compose.yml getting generated after initialization? 
I suspect, it considers "besu" as a single service like "geth" it should not do that.
It works fine on two different machines when I tested it. Can you look into the difference it makes in the cli when we use -b vs --blockchain-provider flag?

**Comment by sukrut29** [comment]
> @sukrut29 Thank you for contributing this! I will start reviewing it. In the meantime, it looks like the DCO bot has flagged that some or all commits do not have proper sign-off. Could you please check here for details: https://github.com/hyperledger/firefly-cli/pull/117/checks?check_run_id=4082447375
> 
> Thanks!

I have made sure now that the signing is in accordance to the guidelines

**Comment by nguyer** [comment]
> Can you share the docker-compose.yml getting generated after initialization?
Sure, I'll post the generated file.

> Can you look into the difference it makes in the cli when we use -b vs --blockchain-provider flag?
`-b` is just the shorthand version of `--blockchain-provider`. Cobra treats them as the same thing, so there should be no difference.

**Comment by nguyer** [comment]
[docker-compose.yml.txt](https://github.com/hyperledger/firefly-cli/files/7468061/docker-compose.yml.txt)

**Comment by nguyer** [comment]
```
version: "2.1"
services:
  besu: {}
 ```
 
 This is likely the problem. The `{}` looks out of place here.

**Comment by sukrut29** [comment]
> Edit: I have removed some of my previous comments, because I was accidentally testing on the wrong branch. Sorry.

No problem, please test now on firefly-on-besu-ibft2 branch.
I have removed the need for the devs to pull the branch with the Config folder, all config files are now compiled with the ff binary and saved at compile time.

**Comment by nguyer** [comment]
Sukrut and I chatted directly about this, but I cannot get a besu stack generated by this branch to run on my machine. It appears that services may be deadlocking waiting for each other to start and docker becomes pretty unresponsive while starting services. That was as far as I got with testing this branch.

**Comment by nguyer** [comment]
@sukrut29 Since we merged the other Besu PR do you think we need this one still?

**Comment by sukrut29** [comment]
> @sukrut29 Since we merged the other Besu PR do you think we need this one still?

I think you are right, I ll close this PR.

**Pull request closed without merging**
