### PR TITLE
Switch from https to ffdx

### PR DESCRIPTION
**Pull request by gabriel-indik**
Signed-off-by: Gabriel Indik <gabriel.indik@kaleido.io>

### CODE REVIEW

**Comment by nguyer** [comment]
I think this also means any old config files using `https` instead of `ffdx` in existing FireFly installations will no longer work. Are we okay with that?

**Comment by gabriel-indik** [comment]
@nguyer generating config files with the new agreed term shouldn't cause problems. The issue could potentially take place with https://github.com/hyperledger/firefly/pull/590. The way things are today, FF is broken when `ffdx` is used in the configuration file. Note also that a warning is shown in the console about using `https` independently of what is present in the configuration file. We may need to include additional logic in FF core to properly support both scenarios.

**Comment by hfuss** [comment]
Closing https://github.com/hyperledger/firefly-cli/pull/154 in favor of this one

**Comment by gabriel-indik** [comment]
Looking further into the code:

### Current behavior
- The CLI generates the `dataexchange` section in the configuration file using `https` and without specifying the `type`.
- FF Core defaults to `https` when the type is missing.
- If the `dataexchange` section is instead `ffdx` then the type must be specified, otherwise FF core will fail to read the configuration file.

### Changes added to the CLI
 - The `dataexchange` section in the configuration file now uses `ffdx` instead of `https`
 - The `type` is now included (value `ffdx`) to ensure FF core can load the configuration file successfully

**Comment by peterbroadhurst** [comment]
> The `type` is now included (value `ffdx`) to ensure FF core can load the configuration file successfully

The fact this is necessary seem like a bug in FF Core to me.

**Comment by peterbroadhurst** [comment]
I'm going to take a crack at a change extending https://github.com/hyperledger/firefly/pull/590 that solves ^^^

**Review by peterbroadhurst — APPROVED** [review]
Worked through the implications here, and we have an e2e run through on https://github.com/hyperledger/firefly/pull/590 that confirms we still accept the `https` generated by the CLI before this change.

**Pull request merged**
