### PR TITLE
feature enhancement and code cleaning.

### PR DESCRIPTION
**Pull request by tobigiwa**
This commit includes:

1) a new  "docs" command to generate markdown documentations of all command on rootCmd.
The list of generated markdown is put in the folder directory "./docs/command_docs" as default or any location specified by the user as arguement to the "docs" command.

2) included a function "listStacks" to add completion for stacks.

// listStacks return a list of available stacks on the local machine from "$HOME/.firefly/stack". The function
// is intended to add completion to command that require  as arguement.
//
// Expected usage:
//
//	var Cmd = &cobra.Command{
//			...
//			ValidArgsFunction: listStacks,
//			...

3) removed "cmd/ls.go", the command already exist as an alias to the command "list" in "cmd/list.go" with the same implementation.

### CODE REVIEW

**Comment by nguyer** [comment]
This is great, thanks! Do you mind adding a description and title for the PR? I need to get another PR merged in this repo, then I can run the workflows against this one. If they pass, I'm happy to approve and merge this.

**Comment by tobigiwa** [comment]
I'll be on it soon, thanks.

**Comment by tobigiwa** [comment]
> Hey, sorry about the build issues. Those have been resolved in `main` now so if you merge `main` back into your branch you should get a green build.

I have done that. 👍🏿

**Comment by tobigiwa** [comment]
Hey @nguyer any correction you would like me making?

**Pull request closed without merging**
