### PR TITLE
cmd tests implementations

### PR DESCRIPTION
**Pull request by Philip-21**
This pr fixes for #7

### CODE REVIEW

**Comment by Philip-21** [comment]
@nguyer I have been able to create vast amount of unit tests here . This can be merged

**Review by nguyer — CHANGES_REQUESTED** [review]
This is great. Thank you for adding so many tests! I think we should do two things before this could be merged.

1. Can you merge the `fix-tests` branch into this one? https://github.com/hyperledger/firefly-cli/pull/288
I fixed a number of issues with the existing tests in this branch, including making them run as a part of the CI workflow (using `make`). I want to make sure we have all tests passing before we merge.

2. Can you make sure that none of the tests leave a modified git tree when they are done? Right now it looks like some of the tests write a file that is not cleaned up at the end of the test. You can refer to my branch/PR for how to use `t.TempDir()` in tests to solve this issue

**Comment by Philip-21** [comment]
> This is great. Thank you for adding so many tests! I think we should do two things before this could be merged.
> 
> 1. Can you merge the `fix-tests` branch into this one? [Fix tests #288](https://github.com/hyperledger/firefly-cli/pull/288)
>    I fixed a number of issues with the existing tests in this branch, including making them run as a part of the CI workflow (using `make`). I want to make sure we have all tests passing before we merge.
> 2. Can you make sure that none of the tests leave a modified git tree when they are done? Right now it looks like some of the tests write a file that is not cleaned up at the end of the test. You can refer to my branch/PR for how to use `t.TempDir()` in tests to solve this issue

I will do these

**Comment by Philip-21** [comment]
> Wonderful! Thank you so much for contributing this!

My pleasure

**Pull request merged**
