### PR TITLE
Enable an instance of tezossigner to deploy a contract using FF core API

### PR DESCRIPTION
**Pull request by alex-semenyuk**
Related PRs to [firefly](https://github.com/hyperledger/firefly/pull/1481) and [firefly-tezosconnect](https://github.com/hyperledger/firefly-tezosconnect/pull/36)

### CODE REVIEW

**Review by denisandreenko — APPROVED** [review]

**Comment by nguyer** [comment]
Hey @alex-semenyuk I'm happy to include this, but I'm unclear on how someone would use this command with these changes. Do you also need to add a `ff deploy tezos` sub command?

**Comment by alex-semenyuk** [comment]
> Hey @alex-semenyuk I'm happy to include this, but I'm unclear on how someone would use this command with these changes. Do you also need to add a `ff deploy tezos` sub command?

Hey @nguyer 
As I mentioned at description it's required for new implemented deploy API. We need to add 'origination' as allowed transaction value for the given address config [Originating means the same as Deploying contract](https://docs.tezos.com/smart-contracts/deploying#:~:text=In%20Tezos%2C%20deploying%20a%20smart,holds%20the%20smart%20contract's%20script.)

**Comment by nguyer** [comment]
Okay so this is just making the change to enable an instance of tezossigner to deploy a contract that is created by the FireFly CLI? And we could have separate PR later to allow the user to actually deploy a contract with the FireFly CLI?

**Comment by denisandreenko** [comment]
@nguyer you're right. 
It unblocks tezossigner for a contract deployment, so we can use FF core API to make a deployment request.
CLI support will be added next.

**Comment by alex-semenyuk** [comment]
@nguyer @denisandreenko Thanks!
Changed the name of this PR to avoid confusion. Also going to add support deploying via CLI in the next iterations.

**Review by nguyer — APPROVED** [review]

**Pull request merged**
